name = "aeon-news"
main = "worker.js"
compatibility_date = "2024-09-01"

[vars]
ADMIN_EMAIL = "AEONAdaptivesNetzwerk@proton.me"
FROM_EMAIL  = "newsletter@deinedomain.tld"   # Domain muss zu dir gehören
API_KEY     = "dein-admin-key"

[[kv_namespaces]]
binding = "SUBS"
id = "kv_id_in_prod"
preview_id = "kv_id_in_preview"
