name = "aeon-news-worker"
main = "worker.js"
compatibility_date = "2024-10-01"

[vars]
# nix hier

[kv_namespaces]
  [[kv_namespaces.bindings]]
  binding = "AEON_SUBS"
  id = "YOUR_KV_ID"

[vars]
RESEND_API_KEY = "YOUR_RESEND_API_KEY"
